config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users, :controllers => {:registrations => :registrations}
  root to:'pages#home'
  get 'comments/index'
  get 'comments/new'
  get 'comments/edit'
  get 'comments/destroy'
  get 'comments/create'
  get 'comments/update'
  get 'news_report/index'
  get 'news_report/show'
  get 'news_report/new'
  get 'news_report/edit'
  get 'profile/index'
  get 'profile/show'
  get 'profile/new'
  get 'profile/edit'
  resources :users do
    resources :profiles do
      resources :news_reports do
        resources :comments
      end
    end
  end
  # resources :news_writers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/news', :controller=>'news', :action=>'get_news'
  get '/newsreports', :controller=>'news_reports', :action=>'all_reports'
  get '/newswriters', :controller=>'profiles', :action=>'all_profiles'
  get '/search', :controller=>'news', :action=>'search_news'
  get '/follow', :controller=>'follow', :action=>'following'
  get '/favourites', :controller=>'favourites', :action=>'my_favourites'
end

app/models/news_report.rb
class NewsReport < ApplicationRecord
  belongs_to :profile
  has_many :comments
  validates :title, presence: true, length: { maximum: 100, too_long: "%{count}characters are allowed" }
  validates :category, presence: true
  validates :content, presence: true
end

app/controllers/news_reports_controller.rb
require('sentimentanalyzer')

class NewsReportsController < ApplicationController

  SentimentAnalyzer.loadProfaneWords(Rails.root.join('lib/word_bank/bad-words.csv'))

  def index
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @news_reports = @profile.news_reports
  end

  def show
    @current_user = User.find(session["warden.user.user.key"][0][0])
    @current_profile_id = @current_user.profile.id
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @news_report = @profile.news_reports.find(params[:id])
    @comments = @news_report.comments
    
  end

  def new
    @user = User.find(params[:user_id])
    @profile =  @user.profile
    @current_user = User.find(session["warden.user.user.key"][0][0])
    @current_profile = @current_user.profile
    @news_report = @current_profile.news_reports.build
  end

  def create 
    @user = User.find(params[:user_id])
    @createdby = @user.username
    @profile = @user.profile
    @current_user = User.find(session["warden.user.user.key"][0][0])
    @current_profile = @current_user.profile
    @createdby = @current_user.username

    @title = params[:title]
    @category = params[:category]
    @content = params[:content]

    @news_report = @current_profile.news_reports.build(params.require(:news_report).permit(:title, :category, :content))
    if SentimentAnalyzer.profaneWordsFilter(@news_report.title) == true && SentimentAnalyzer.profaneWordsFilter(@news_report.category) == true && SentimentAnalyzer.profaneWordsFilter(@news_report.content) == true
      @news_report.createdby = @createdby
      if @news_report.save
        redirect_to user_profile_news_report_url(@current_user.id, @current_profile.id, @news_report.id)
      else 
        render :action => "new"
      end
    else 
      redirect_to new_user_profile_news_report_url(@current_user.id, @current_profile), flash: { alert: "Offensive language is forbidden!" }
    end
     
  end

  def edit
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @current_user = User.find(session["warden.user.user.key"][0][0])
    @current_profile = @current_user.profile
    @news_report = @current_profile.news_reports.find(params[:id])
  end

  def update 
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @current_user = User.find(session["warden.user.user.key"][0][0])
    @current_profile = @current_user.profile
    @title = params[:title]
    @category = params[:category]
    @content = params[:content]
    @news_report = @current_profile.news_reports.find(params[:id])
    @createdby = @news_report.createdby
    if @news_report.update_attributes(params.require(:news_report).permit(:title, :category, :content))
      @news_report.createdby = @createdby
      redirect_to user_profile_news_report_url
    else 
      render :action => "edit"
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @news_report = @profile.news_reports.find(params[:id])
    @news_report.destroy
    respond_to do |format|
      format.html {redirect_to user_profile_news_reports_url }
      format.xml { head :ok }
    end
  end

  def all_reports
    @news_reports = NewsReport.order(created_at: :desc)
  end
end

app/helpers/news_report_helper.rb
module NewsReportHelper
end

app/views/news_reports/_form.html.erb
<%= form_for([@user, @profile, @news_report]) do |f| %>
    <% if @news_report.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@news_report.errors.count, "error")%>
            prohibited this review from being saved:</h2>
            <ul>
                <% @news_report.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
        <% end %>
        <div class="form-row">
            <div class="form-group col-md-8">
                <%= f.label :title, 'Title' %>
                <%= f.text_field :title , class: 'form-control'%>
            </div>
            <div class="form-group col-md-4">
                <%= f.label :category, 'Category' %>
                <%= f.text_field :category, class: 'form-control'%>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :content, 'Content' %>
            <%= f.text_area :content, class: 'form-control', rows: '20'%>
        </div>
        <div class="form-group">
            <%= f.submit ('Create'), class: 'btn btn-primary' %>
        </div>
    </div>
<% end %>

app/views/news_reports/_links.erb
<% if current_user %>
    <%= link_to 'Sing out', destroy_user_session_path, method: :delete %>
<% else %> 
    <p>Please sign in</p>
    <%= link_to 'Sign in', new_user_session_path %>
    <p>Do not have an account?</p>
    <%= link_to 'Sign up', new_user_registration_path %>
<% end %> 

app/views/news_reports/all_reports.html.erb
<h1 class="heading">News reports</h1>
<div class="row">
    <% if @news_reports %>
        <% for news_report in @news_reports %>
        <div class="col-lg-4 card-wrapper"> 
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"><b>Title:</b> <%= news_report.title %></h5>
                    <h6 class="card-subtitle"><b>Category:</b> <%= news_report.category %></h6><br/>
                    <p><%= news_report.content[0..150].gsub(/\s\w+\s*$/,'...') %></p>
                    <%= link_to 'Read more', user_profile_news_report_url(Profile.find(news_report.profile.id).user_id, news_report.profile, news_report)
                    %>
                    <% if news_report.createdby %>
                        <footer class="blockquote-footer">
                            <cite><%= news_report.createdby %></cite>
                        </footer>
                    <% end %>
                </div>
            </div>
        </div>
        <% end %>   
    <% else %>
        <h1>No news</h1>
    <% end %>
</div>

app/views/news_reports/edit.html.erb
<h1 class="heading">Edit news report</h1>
<%= form_for :news_report, url: user_profile_news_report_url(@current_user, @current_profile, @news_report), method: :put do |f| %>
    <% if @news_report.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@news_report.errors.count, "error")%>
            prohibited this review from being saved:</h2>
            <ul>
                <% @news_report.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
        <% end %>
        <div class="form-row">
            <div class="form-group col-md-8">
                <%= f.label :title, 'Title' %>
                <%= f.text_field :title , class: 'form-control'%>
            </div>
            <div class="form-group col-md-4">
                <%= f.label :category, 'Category' %>
                <%= f.text_field :category, class: 'form-control'%>
            </div>
        </div>
        <div class="form-group">
            <%= f.label :content, 'Content' %>
            <%= f.text_area :content, class: 'form-control', rows: '20'%>
        </div>
        <div class="form-group">
            <%= f.submit ('Edit'), class: 'btn btn-primary' %>
        </div>
    </div>
<% end %>

app/views/news_reports/index.html.erb
<h1 class="heading">Your reports</h1>
<% if @news_reports %>
    <div class="row">
        <% for news_report in @news_reports %>
        <div class="col-lg-4 card-wrapper"> 
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"><b>Title:</b> <%= news_report.title %></h5>
                    <h6 class="card-subtitle"><b>Category:</b> <%= news_report.category %></h6><br/>
                    <p><%= news_report.content[0..150].gsub(/\s\w+\s*$/,'...') %></p>
                    <%= link_to 'Read more', user_profile_news_report_url(Profile.find(news_report.profile.id).user_id, news_report.profile, news_report)
                    %>
                    <% if news_report.createdby %>
                        <footer class="blockquote-footer">
                            <cite><%= news_report.createdby %></cite>
                        </footer>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>   
</div>
<% end %>

app/views/news_reports/new.html.erb
<h1 class="heading">Create news report</h1>
<%= render 'form' %>

app/views/news_reports/show.html.erb
<h1 class="heading">Report title in <%= @news_report.title %></h1>
<div>
    <h3>Category: <%= @news_report.category %></h2>
    <h4>Written by: <%= @news_report.createdby %></h3>
</div>
<div>
    <p>
        <%= @news_report.content %>
    </p>
    <% if @current_profile_id == @news_report.profile_id %>
        <div class="row">
            <div class="col-lg-1"> 
                <%= link_to 'Edit', edit_user_profile_news_report_path(@user,   @profile, @news_report), class: 'nav-link custom-nav'%>
            </div>

            <div class="col-lg-2"> 
                <%= link_to 'Delete', user_profile_news_report_url, method: :delete, class: 'nav-link custom-nav'%>
            </div>
        </div>
    <% end %>
</div>
<div class="comment-input-section">
    <%= form_tag(user_profile_news_report_comments_url(@user, @profile, @news_report), method: "post") do %>
        <div class="form-row">
            <div class="form-group col-lg-10">
                <%= text_area_tag :user_comment, rows='10', class: 'form-control' %>
            </div>
            <div class="form-group col-lg-2">
                <%= submit_tag("comment", class: 'form-control comment-btn')%>
            </div>
        </div>
    <% end %>
</div>
<% if @comments %>
    <% for @comment in @comments %>
        <div class="comment-section">
            <div class="card comment-cards">
                <div class="card-body">
                    <p><%= @comment.comment %></p>
                    <% if @comment.sentiment == 'Positive'%>
                        <p>Sentiment: &#128516;</p>
                    <% elsif @comment.sentiment == 'Negative' %>
                        <p>Sentiment: &#129324;</p>
                    <% elsif @comment.sentiment == 'Neutral' %>
                        <p>Sentiment: &#128566;</p>
                    <% end %>
                    <p>Posted by: <%= @comment.createdby %></p>
                    <% if @current_profile_id == @comment.profile_id %>
                        <div class="row">
                            <div class="col-lg-2">
                                <%= link_to 'Edit' ,edit_user_profile_news_report_comment_url(@user, @profile, @news_report, @comment), class: 'nav-link'%>
                            </div>
                            <div class="col-lg-2 ">
                                <%= link_to 'Delete', user_profile_news_report_comment_url(@user, @profile, @news_report, @comment), :confirm => 'Are you sure?', :method => :delete, class: 'nav-link comment-buttons'%>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>  
    <% end %>
<% end %>