config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users, :controllers => {:registrations => :registrations}
  root to:'pages#home'
  get 'comments/index'
  get 'comments/new'
  get 'comments/edit'
  get 'comments/destroy'
  get 'comments/create'
  get 'comments/update'
  get 'news_report/index'
  get 'news_report/show'
  get 'news_report/new'
  get 'news_report/edit'
  get 'profile/index'
  get 'profile/show'
  get 'profile/new'
  get 'profile/edit'
  resources :users do
    resources :profiles do
      resources :news_reports do
        resources :comments
      end
    end
  end
  # resources :news_writers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/news', :controller=>'news', :action=>'get_news'
  get '/newsreports', :controller=>'news_reports', :action=>'all_reports'
  get '/newswriters', :controller=>'profiles', :action=>'all_profiles'
  get '/search', :controller=>'news', :action=>'search_news'
  get '/follow', :controller=>'follow', :action=>'following'
  get '/favourites', :controller=>'favourites', :action=>'my_favourites'
end

app/controllers/news_controller.rb
require 'open-uri'
require 'json'
require 'breaking_news_apis'

class NewsController < ApplicationController 
    def get_news
        @news = BreakingNewsApis.instance.get_news
        @previous_search = cookies[:previous_search]
        @previous_search = @previous_search.to_s
        @recommended_news = BreakingNewsApis.instance.recommendation(@previous_search)
    end

    def search_news 
        @search_value = params[:search_value]
        cookies[:previous_search] = @search_value
        @news = BreakingNewsApis.instance.search(@search_value)
        @news_reports = NewsReport.where({ category: @search_value})
    end
end

app/views/news/get_news.html.erb
<%= stylesheet_link_tag 'style' %>
<div class="container"> 
  <h1 class="heading">Breaking news</h1>
  <div>
    <%= form_tag(search_url, method: 'get', class: 'form') do %>
      <div class="form-row">
          <div class="form-group col-lg-10">
              <%= text_field_tag :search_value, rows='10', class: 'form-control' %>
          </div>
          <div class="form-group col-lg-2">
              <%= submit_tag("Search", class: 'form-control comment-btn')%>
          </div>
      </div>
    <% end %>
  </div>

  <div>
    <% if @previous_search != '' %>
      <h3>Becuase you viewed: <%= @previous_search %> </h3>
      <% @recommended_news["newsApiRecommendationResponse"]["articles"].each do |content| %>
        <div class="card-content-container"> 
          <div class="card">
            <div class="card-header">  
              <h5><%= content["title"] %></h5>
              <h6>- <%= content["source"]["name"] %></h6>
            </div>
            <div class="card-body"> 
              <p><%= content["description"] %></p>
              <p><%= content["publishedAt"] %></p>
              <a href=<%= content["url"] %> class="btn btn-primary">Link</a>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <h3>Daily news</h3>
  <% @news["newsApiResponse"]["articles"].each do |content| %>
    <div class="card-content-container"> 
      <div class="card">
        <div class="card-header">  
          <h5><%= content["title"] %></h5>
          <h6>- <%= content["source"]["name"] %></h6>
        </div>
        <div class="card-body"> 
          <p><%= content["description"] %></p>
          <p><%= content["publishedAt"] %></p>
          <a href=<%= content["url"] %> class="btn btn-primary">Link</a>
        </div>
      </div>
    </div>
  <% end %>

  <% @news["guardianApiResponse"]["response"]["results"].each do |content| %>
    <div class="card-content-container">
      <div class="card">
        <div class="card-header">
          <h5><%= content["webTitle"]%></h5>
        </div>
        <div class="card-body"> 
          <p><%= content["type"]%></p>
          <p><%= content["sectionName"]%></p>
          <p><%= content["webPublicationDate"]%></p>
          <a href=<%= content["webUrl"] %> class="btn btn-primary">Link</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/news/search_news.html.erb
<%= stylesheet_link_tag 'style' %>
<div class="container"> 
  <h1 class="heading">Search news</h1>
  <div>
    <%= form_tag(search_url, method: 'get', class: 'form') do %>
      <div class="form-row">
          <div class="form-group col-lg-10">
              <%= text_field_tag :search_value, rows='10', class: 'form-control' %>
          </div>
          <div class="form-group col-lg-2">
              <%= submit_tag("Search", class: 'form-control comment-btn')%>
          </div>
      </div>
    <% end %>
  </div>
  <% if @news_reports %>
    <div class="row">
      <% for news_report in @news_reports %> 
        <div class="col-lg-4 card-wrapper"> 
          <div class="card" style="width: 18rem;">
              <div class="card-body">
                  <h5 class="card-title"><b>Title:</b> <%= news_report.title %></h5>
                  <h6 class="card-subtitle"><b>Category:</b> <%= news_report.category %></h6><br/>
                  <p><%= news_report.content[0..150].gsub(/\s\w+\s*$/,'...') %></p>
                  <%= link_to 'Read more', user_profile_news_report_url(Profile.find(news_report.profile.id).user_id, news_report.profile, news_report)
                  %>
                  <% if news_report.createdby %>
                      <footer class="blockquote-footer">
                          <cite><%= news_report.createdby %></cite>
                      </footer>
                  <% end %>
              </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>   

  <% @news["newsApiSearchResponse"]["articles"].each do |content| %>
    <div class="card-content-container"> 
      <div class="card">
        <div class="card-header">  
          <h5><%= content["title"] %></h5>
          <h6>- <%= content["source"]["name"] %></h6>
        </div>
        <div class="card-body"> 
          <p><%= content["description"] %></p>
          <p><%= content["publishedAt"] %></p>
          <a href=<%= content["url"] %> class="btn btn-primary">Link</a>
        </div>
      </div>
    </div>
  <% end %>

  <% @news["guardianApiSearchResponse"]["response"]["results"].each do |content| %>
    <div class="card-content-container">
      <div class="card">
        <div class="card-header">
          <h5><%= content["webTitle"]%></h5>
        </div>
        <div class="card-body"> 
          <p><%= content["type"]%></p>
          <p><%= content["sectionName"]%></p>
          <p><%= content["webPublicationDate"]%></p>
          <a href=<%= content["webUrl"] %> class="btn btn-primary">Link</a>
        </div>
      </div>
    </div>
  <% end %>
</div>