config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users, :controllers => {:registrations => :registrations}
  root to:'pages#home'
  get 'comments/index'
  get 'comments/new'
  get 'comments/edit'
  get 'comments/destroy'
  get 'comments/create'
  get 'comments/update'
  get 'news_report/index'
  get 'news_report/show'
  get 'news_report/new'
  get 'news_report/edit'
  get 'profile/index'
  get 'profile/show'
  get 'profile/new'
  get 'profile/edit'
  resources :users do
    resources :profiles do
      resources :news_reports do
        resources :comments
      end
    end
  end
  # resources :news_writers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/news', :controller=>'news', :action=>'get_news'
  get '/newsreports', :controller=>'news_reports', :action=>'all_reports'
  get '/newswriters', :controller=>'profiles', :action=>'all_profiles'
  get '/search', :controller=>'news', :action=>'search_news'
  get '/follow', :controller=>'follow', :action=>'following'
  get '/favourites', :controller=>'favourites', :action=>'my_favourites'
end

app/views/layouts/_alerts.html.erb
<% if notice %>
    <div class="notice alert alert-primary" role="alert"><%= notice %></div>
<% elsif alert %>
    <div class="alert alert-warning"><%= alert %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<ul class="nav justify-content-end navbar">
  <% if current_user && current_user.profile %>
    <li class="nav-item">
      <%= link_to "Breaking News", news_url, :class => 'nav-link navbar-brand'%>
    </li>
    <li class="nav-item">
      <%= link_to "Favourites", favourites_url, :class => 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to "News reports", newsreports_url, :class => 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to "Your reports", user_profile_news_reports_url(current_user.id, current_user.profile.id), :class => 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to "Create reports",  new_user_profile_news_report_url(current_user.id, current_user.profile.id), :class => 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to "News Writers", newswriters_url, :class => 'nav-link'%>
    </li>
    <li class="nav-item">
      <%= link_to "Account",  user_profiles_url(current_user), :class => 'nav-link'%>
    </li>
    <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_url, :class => 'nav-link', method: :delete%>
    </li>
    <% elsif !current_user %>
      <li class="nav-item">
        <%= link_to 'Sign in', new_user_session_path, :class => 'nav-link'%>
      </li>
    <% else %>
    <li class="nav-item">
      <%= link_to 'Cancel', user_registration_url, :class => 'nav-link', method: :delete%>
    </li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="jquery-3.4.1.min.js"></script>
  </head>
 
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>